# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_auto_20170224_1116'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='has_courses', to='login_reg.User'),
        ),
    ]
