# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26fb74f0e1e1942ea72ffa603ba84377e242bbb7d20e0ed5ff2a55ad2f2546003a3b3bb85197e030cfee6e8f383f216fcbf2eaf287d7c8770841d1aff7abb0e

test:
  secret_key_base: 18d608ece7bcddb99ede5d1a7f86a5f9abc2432d03ff137495ceee89caefe40c426a3475945297f726377572a7be38640bbdf459d0e5129ec40d0130545c7e6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
