# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170224_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='secre1',
            new_name='secret',
        ),
    ]
