# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f46dcd68401ea11148e9e2ba62edd8e011dd2e54996e30d5497c2080f3e94c22bda825e98cd235c7da3647535c552a96cbcb3cf9dfa3ba551825f2c5b6082e1e

test:
  secret_key_base: 59f801622d22f26318f5bd9bb4e10f3b3ed13921da17b80248b185ee34171193e06b9133645a57a8dc1d88add1571a993e420cd9374cb608600d37f1cf996631

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
